# Generated by Django 5.2.16 on 2026-07-19 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bingos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BingoDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("opens", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("unlikes", models.PositiveIntegerField(default=0)),
                ("starts", models.PositiveIntegerField(default=0)),
                ("completes", models.PositiveIntegerField(default=0)),
                ("resets", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                (
                    "bingo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="bingos.bingo",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "bingo"], name="analytics_b_date_872c63_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bingo", "date"), name="unique_bingo_daily_metric"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InteractionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("anonymous_id_hash", models.CharField(blank=True, max_length=64)),
                (
                    "client_event_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("client", "Client"), ("server", "Server")],
                        db_index=True,
                        default="client",
                        max_length=12,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("view", "View"),
                            ("open", "Open"),
                            ("like", "Like"),
                            ("unlike", "Unlike"),
                            ("start", "Start"),
                            ("complete", "Complete"),
                            ("reset", "Reset"),
                            ("share", "Share"),
                            ("comment", "Comment"),
                            ("follow", "Follow"),
                            ("search", "Search"),
                            ("tag_interaction", "Tag interaction"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bingo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interaction_events",
                        to="bingos.bingorevision",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_events",
                        to="bingos.tag",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["bingo", "event_type", "-occurred_at"],
                        name="analytics_i_bingo_i_401a95_idx",
                    ),
                    models.Index(
                        fields=["source", "event_type", "-occurred_at"],
                        name="analytics_i_source_ac9349_idx",
                    ),
                    models.Index(
                        fields=["actor", "event_type", "-occurred_at"],
                        name="analytics_i_actor_i_242cc8_idx",
                    ),
                    models.Index(
                        fields=["tag", "event_type", "-occurred_at"],
                        name="analytics_i_tag_id_8f2a45_idx",
                    ),
                    models.Index(
                        fields=["anonymous_id_hash", "-occurred_at"],
                        name="analytics_i_anonymo_f4cace_idx",
                    ),
                ],
            },
        ),
    ]
