# Generated by Django 5.2.17 on 2026-09-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_redact_search_event_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionevent',
            name='event_type',
            field=models.CharField(choices=[('impression', 'Impression'), ('view', 'View'), ('open', 'Open'), ('like', 'Like'), ('unlike', 'Unlike'), ('start', 'Start'), ('complete', 'Complete'), ('reset', 'Reset'), ('share', 'Share'), ('comment', 'Comment'), ('follow', 'Follow'), ('search', 'Search'), ('tag_interaction', 'Tag interaction'), ('page_view', 'Page view'), ('cta', 'Primary action')], db_index=True, max_length=32),
        ),
    ]
