version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - infrastructure

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - backend
      - infrastructure

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - frontend
      - infrastructure

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
