# Generated by Django 5.2.16 on 2026-07-19 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bingos", "0001_initial"),
        ("media_assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bingo", "Bingo board"),
                            ("account_data", "Account data"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("png", "PNG"), ("pdf", "PDF"), ("zip", "ZIP")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "bingo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_jobs",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "output_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to="media_assets.mediaasset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_jobs",
                        to="bingos.bingorevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["owner", "status", "-created_at"],
                        name="exports_exp_owner_i_72509d_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="exports_exp_status_b76416_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("owner", "kind", "idempotency_key"),
                        name="unique_export_idempotency_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("bingo__isnull", False),
                                ("kind", "bingo"),
                                ("revision__isnull", False),
                            ),
                            models.Q(
                                ("bingo__isnull", True),
                                ("kind", "account_data"),
                                ("revision__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="export_target_matches_kind",
                    ),
                ],
            },
        ),
    ]
