import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import { connection } from "next/server";
import type { ReactNode } from "react";

import { AppHeader } from "@/components/layout/app-header";
import { AuthDialog } from "@/components/auth/auth-dialog";
import { DevelopmentFeedback } from "@/components/layout/development-feedback";
import { BrowserErrorObserver } from "@/components/layout/browser-error-observer";
import { PageActivity } from "@/components/layout/page-activity";
import { SiteFooter } from "@/components/layout/site-footer";
import { absoluteSiteUrl, isPublicProduction, siteUrl } from "@/lib/site";
import { getServerSessionSnapshot } from "@/lib/api/server";

import "./globals.css";

export const metadata: Metadata = {
  metadataBase: siteUrl(),
  title: {
    default: "Not Enough Bingo",
    template: "%s — Not Enough Bingo",
  },
  description: "Create, play, and share community bingo boards.",
  robots: isPublicProduction() ? undefined : { index: false, follow: false },
  openGraph: {
    type: "website",
    siteName: "Not Enough Bingo",
    images: [
      {
        url: absoluteSiteUrl("/opengraph-image"),
        width: 1200,
        height: 630,
        alt: "Not Enough Bingo — create, play, and share community bingo boards",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: [absoluteSiteUrl("/opengraph-image")],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
  themeColor: "#ffffff",
};

export default async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  // Per-request rendering lets Next apply the nonce generated by proxy.ts to
  // every framework script and inline style element.
  await connection();
  const session = await getServerSessionSnapshot((await cookies()).toString());
  return (
    <html lang="en">
      <body>
        <a className="skip-link" href="#main-content">
          Skip to content
        </a>
        <AppHeader
          initialUserId={session === null ? undefined : (session.user?.id ?? null)}
          initialLogoutEvent={session?.logout_event}
        />
        <PageActivity />
        <BrowserErrorObserver />
        <AuthDialog />
        {children}
        <SiteFooter />
        {process.env.NODE_ENV === "development" && process.env.AGENTATION_ENABLED !== "false" ? (
          <DevelopmentFeedback />
        ) : null}
      </body>
    </html>
  );
}
