import { Agentation } from "agentation";
import type { Metadata, Viewport } from "next";
import { connection } from "next/server";
import type { ReactNode } from "react";

import { AppHeader } from "@/components/layout/app-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { absoluteSiteUrl, isPublicProduction, siteUrl } from "@/lib/site";

import "./globals.css";

export const metadata: Metadata = {
  metadataBase: siteUrl(),
  title: {
    default: "Not Enough Bingo",
    template: "%s — Not Enough Bingo",
  },
  description: "Create, play, and share community bingo boards.",
  robots: isPublicProduction() ? undefined : { index: false, follow: false },
  openGraph: {
    type: "website",
    siteName: "Not Enough Bingo",
    images: [
      {
        url: absoluteSiteUrl("/opengraph-image"),
        width: 1200,
        height: 630,
        alt: "Not Enough Bingo — create, play, and share community bingo boards",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: [absoluteSiteUrl("/opengraph-image")],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
  themeColor: "#ffffff",
};

export default async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  // Per-request rendering lets Next apply the nonce generated by proxy.ts to
  // every framework script and inline style element.
  await connection();
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body>
        <a className="skip-link" href="#main-content">
          Skip to content
        </a>
        <AppHeader />
        {children}
        <SiteFooter />
        {process.env.NODE_ENV === "development" && process.env.AGENTATION_ENABLED !== "false" ? (
          <Agentation />
        ) : null}
      </body>
    </html>
  );
}
