# Generated by Django 5.2.16 on 2026-07-19 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar"),
                            ("cover", "Bingo cover"),
                            ("board_background", "Board background"),
                            ("cell_image", "Cell image"),
                            ("bingo_export", "Bingo export"),
                            ("account_export", "Account export"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending upload"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                            ("quarantined", "Quarantined"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("thumbnail", "Thumbnail"),
                            ("generated", "Generated"),
                        ],
                        default="original",
                        max_length=16,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("storage_bucket", models.CharField(blank=True, max_length=128)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("extension", models.CharField(blank=True, max_length=12)),
                ("declared_mime", models.CharField(blank=True, max_length=100)),
                ("detected_mime", models.CharField(blank=True, max_length=100)),
                ("expected_size", models.PositiveBigIntegerField(default=1)),
                ("byte_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "expected_checksum_sha256",
                    models.CharField(blank=True, max_length=64),
                ),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=120)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivatives",
                        to="media_assets.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["owner", "status", "-created_at"],
                        name="media_asset_owner_i_f55cf8_idx",
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="media_asset_status_58e9f6_idx",
                    ),
                    models.Index(
                        fields=["kind", "status", "-created_at"],
                        name="media_asset_kind_b2a0ec_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expected_size__gt", 0)),
                        name="media_expected_size_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("parent__isnull", False)),
                        fields=("parent", "variant"),
                        name="media_unique_parent_variant",
                    ),
                ],
            },
        ),
    ]
