# Generated by Django 5.2.17 on 2026-09-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_mediaasset_processing_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='processing_attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
