# Generated by Django 5.2.16 on 2026-07-19 22:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media_assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bingo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=70)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("size", models.PositiveSmallIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=16,
                    ),
                ),
                (
                    "marking_style",
                    models.CharField(
                        choices=[
                            ("checkmark", "Checkmark"),
                            ("crossout", "Crossout"),
                            ("highlight", "Highlight"),
                        ],
                        default="checkmark",
                        max_length=16,
                    ),
                ),
                ("marking_config", models.JSONField(blank=True, default=dict)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hidden_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("hidden_reason", models.CharField(blank=True, max_length=500)),
                ("view_count", models.PositiveBigIntegerField(default=0)),
                ("like_count", models.PositiveBigIntegerField(default=0)),
                ("comment_count", models.PositiveBigIntegerField(default=0)),
                ("play_count", models.PositiveBigIntegerField(default=0)),
                ("share_count", models.PositiveBigIntegerField(default=0)),
                ("trending_score", models.FloatField(db_index=True, default=0)),
                (
                    "trending_score_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bingos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bingo_backgrounds",
                        to="media_assets.mediaasset",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bingo_covers",
                        to="media_assets.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="BingoRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=70)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("size", models.PositiveSmallIntegerField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "marking_style",
                    models.CharField(
                        choices=[
                            ("checkmark", "Checkmark"),
                            ("crossout", "Crossout"),
                            ("highlight", "Highlight"),
                        ],
                        max_length=16,
                    ),
                ),
                ("marking_config", models.JSONField(blank=True, default=dict)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("document_hash", models.CharField(max_length=64)),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revision_backgrounds",
                        to="media_assets.mediaasset",
                    ),
                ),
                (
                    "bingo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revision_covers",
                        to="media_assets.mediaasset",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_bingo_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("bingo", "-revision_number"),
            },
        ),
        migrations.CreateModel(
            name="BingoCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("row", models.PositiveSmallIntegerField()),
                ("column", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                ("text", models.CharField(blank=True, max_length=100)),
                ("text_color", models.CharField(default="#000000", max_length=7)),
                ("bold", models.BooleanField(default=False)),
                ("italic", models.BooleanField(default=False)),
                ("underline", models.BooleanField(default=False)),
                ("strikethrough", models.BooleanField(default=False)),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                (
                    "background_opacity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
                (
                    "image_opacity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
                ("border_color", models.CharField(default="#000000", max_length=7)),
                ("border_width", models.PositiveSmallIntegerField(default=1)),
                (
                    "border_style",
                    models.CharField(
                        choices=[
                            ("solid", "Solid"),
                            ("dashed", "Dashed"),
                            ("dotted", "Dotted"),
                            ("double", "Double"),
                        ],
                        default="solid",
                        max_length=12,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revision_cells",
                        to="media_assets.mediaasset",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="bingos.bingorevision",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.AddField(
            model_name="bingo",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_bingos",
                to="bingos.bingorevision",
            ),
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("document", models.JSONField(default=dict)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "based_on_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_drafts",
                        to="bingos.bingorevision",
                    ),
                ),
                (
                    "bingo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_bingo_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=60, unique=True),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("usage_count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["hidden_at", "-usage_count", "name"],
                        name="bingos_tag_hidden__fbcc36_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BingoTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bingo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bingo_links",
                        to="bingos.tag",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="BingoRevisionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=60)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_tags",
                        to="bingos.bingorevision",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revision_snapshots",
                        to="bingos.tag",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
        migrations.AddField(
            model_name="bingo",
            name="tags",
            field=models.ManyToManyField(
                related_name="bingos", through="bingos.BingoTag", to="bingos.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="bingorevision",
            index=models.Index(
                fields=["bingo", "-revision_number"],
                name="bingos_bing_bingo_i_2b3272_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bingorevision",
            constraint=models.UniqueConstraint(
                fields=("bingo", "revision_number"), name="unique_bingo_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="bingorevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gte", 3), ("size__lte", 10)),
                name="revision_size_between_3_and_10",
            ),
        ),
        migrations.AddIndex(
            model_name="bingocell",
            index=models.Index(
                fields=["revision", "position"], name="bingos_bing_revisio_61b604_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bingocell",
            constraint=models.UniqueConstraint(
                fields=("revision", "row", "column"),
                name="unique_revision_cell_coordinate",
            ),
        ),
        migrations.AddConstraint(
            model_name="bingocell",
            constraint=models.UniqueConstraint(
                fields=("revision", "position"), name="unique_revision_cell_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="bingocell",
            constraint=models.UniqueConstraint(
                fields=("revision", "public_id"), name="unique_revision_cell_public_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="bingocell",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("background_opacity__gte", 0), ("background_opacity__lte", 1)
                ),
                name="cell_background_opacity_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="bingocell",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("image_opacity__gte", 0), ("image_opacity__lte", 1)
                ),
                name="cell_image_opacity_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="bingocell",
            constraint=models.CheckConstraint(
                condition=models.Q(("border_width__lte", 12)),
                name="cell_border_width_max_12",
            ),
        ),
        migrations.AddIndex(
            model_name="draft",
            index=models.Index(
                fields=["saved_by", "-updated_at"],
                name="bingos_draf_saved_b_ecf98c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="draft",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="draft_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="bingotag",
            constraint=models.UniqueConstraint(
                fields=("bingo", "tag"), name="unique_bingo_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="bingotag",
            constraint=models.UniqueConstraint(
                fields=("bingo", "position"), name="unique_bingo_tag_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="bingotag",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__lt", 15)),
                name="bingo_tag_position_under_15",
            ),
        ),
        migrations.AddConstraint(
            model_name="bingorevisiontag",
            constraint=models.UniqueConstraint(
                fields=("revision", "position"), name="unique_revision_tag_position"
            ),
        ),
        migrations.AddIndex(
            model_name="bingo",
            index=models.Index(
                fields=["author", "status", "-updated_at"],
                name="bingos_bing_author__1e9558_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bingo",
            index=models.Index(
                fields=["visibility", "status", "hidden_at", "-published_at"],
                name="bingos_bing_visibil_5c720d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bingo",
            index=models.Index(
                fields=["status", "-trending_score", "-published_at"],
                name="bingos_bing_status_a0aeb2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bingo",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gte", 3), ("size__lte", 10)),
                name="bingo_size_between_3_and_10",
            ),
        ),
    ]
