# Generated by Django 5.2.16 on 2026-07-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingos", "0001_initial"),
        ("media_assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftMediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_references",
                        to="media_assets.mediaasset",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_links",
                        to="bingos.draft",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset", "draft"], name="bingos_draf_asset_i_d9d0ff_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "asset"), name="unique_draft_media_asset"
                    )
                ],
            },
        ),
    ]
