# Generated by Django 5.2.16 on 2026-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingos", "0003_bingo_last_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingo",
            name="language",
            field=models.CharField(db_index=True, default="und", max_length=8),
        ),
        migrations.AddField(
            model_name="bingorevision",
            name="language",
            field=models.CharField(default="und", max_length=8),
        ),
    ]
