# Generated by Django 5.2.17 on 2026-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingos', '0004_bingo_language_bingorevision_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingocell',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
