# Generated by Django 5.2.16 on 2026-07-19 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("bingos", "0001_initial"),
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("bingo", "Bingo"),
                            ("comment", "Comment or reply"),
                            ("profile", "Profile"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment or bullying"),
                            ("hate", "Hate speech"),
                            ("sexual", "Sexual content"),
                            ("violence", "Violence"),
                            ("self_harm", "Self-harm"),
                            ("impersonation", "Impersonation"),
                            ("copyright", "Copyright"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("decision", models.CharField(blank=True, max_length=500)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("context_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_moderator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bingo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="social.comment",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("hide", "Hide content"),
                            ("restore", "Restore content"),
                            ("soft_delete", "Soft delete content"),
                            ("suspend_user", "Suspend user"),
                            ("unsuspend_user", "Unsuspend user"),
                            ("dismiss", "Dismiss report"),
                            ("resolve_no_action", "Resolve without action"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("bingo", "Bingo"),
                            ("comment", "Comment or reply"),
                            ("profile", "Profile"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_public_id", models.CharField(max_length=64)),
                ("reason", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="moderation.report",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReportStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=16)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="moderation.report",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "target_type", "created_at"],
                name="moderation__status_b46bc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["assigned_moderator", "status", "created_at"],
                name="moderation__assigne_5cb4eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reporter", "-created_at"],
                name="moderation__reporte_350be5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("bingo__isnull", False),
                        ("comment__isnull", True),
                        ("profile__isnull", True),
                        ("target_type", "bingo"),
                    ),
                    models.Q(
                        ("bingo__isnull", True),
                        ("comment__isnull", False),
                        ("profile__isnull", True),
                        ("target_type", "comment"),
                    ),
                    models.Q(
                        ("bingo__isnull", True),
                        ("comment__isnull", True),
                        ("profile__isnull", False),
                        ("target_type", "profile"),
                    ),
                    _connector="OR",
                ),
                name="report_exactly_one_matching_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("bingo__isnull", False), ("status__in", ("open", "in_review"))
                ),
                fields=("reporter", "bingo"),
                name="unique_active_bingo_report_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("comment__isnull", False), ("status__in", ("open", "in_review"))
                ),
                fields=("reporter", "comment"),
                name="unique_active_comment_report_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("profile__isnull", False), ("status__in", ("open", "in_review"))
                ),
                fields=("reporter", "profile"),
                name="unique_active_profile_report_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["target_type", "target_public_id", "-created_at"],
                name="moderation__target__fc507b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["moderator", "-created_at"],
                name="moderation__moderat_59647a_idx",
            ),
        ),
    ]
