# Generated by Django 5.2.16 on 2026-07-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moderationaction",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("moderate_content", "Can apply moderation actions"),
                    ("view_private_content", "Can inspect private reported content"),
                ],
            },
        ),
    ]
