# Generated by Django 5.2.16 on 2026-07-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="pending_display_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="pending_password_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="pending_username",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
