# Generated by Django 5.2.16 on 2026-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailverification_pending_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_preferences_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_languages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
