# Generated by Django 5.2.17 on 2026-09-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_language_preferences_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('email_verified', 'Email verified'), ('email_changed', 'Email changed'), ('login', 'Login'), ('login_failed', 'Login failed'), ('password_changed', 'Password changed'), ('password_reset', 'Password reset'), ('session_revoked', 'Session revoked'), ('deletion_requested', 'Account deletion requested'), ('account_deleted', 'Account deleted')], max_length=40),
        ),
    ]
