# Generated by Django 5.2.16 on 2026-07-19 22:05

import apps.plays.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bingos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("selected_cells", models.JSONField(default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                ("reset_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bingo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_progress",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="play_progress",
                        to="bingos.bingorevision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="plays_playp_user_id_dc46c5_idx",
                    ),
                    models.Index(
                        fields=["bingo", "revision"],
                        name="plays_playp_bingo_i_f751df_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "bingo"), name="unique_user_bingo_progress"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="play_progress_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SharedResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "share_id",
                    models.CharField(
                        db_index=True,
                        default=apps.plays.models.generate_share_id,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("owner_display_name", models.CharField(max_length=80)),
                ("guest_session_hash", models.CharField(blank=True, max_length=64)),
                ("selected_cells", models.JSONField(default=list)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("public", "Anyone with the link"),
                            ("owner_only", "Owner only"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=16,
                    ),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "bingo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_results",
                        to="bingos.bingo",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_results",
                        to="bingos.bingorevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["bingo", "-created_at"],
                        name="plays_share_bingo_i_a52dce_idx",
                    ),
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="plays_share_owner_i_f7c2af_idx",
                    ),
                    models.Index(
                        fields=["access", "hidden_at", "revoked_at"],
                        name="plays_share_access_c7d7d2_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("guest_session_hash", ""), ("owner__isnull", False)
                            ),
                            models.Q(
                                ("owner__isnull", True),
                                models.Q(("guest_session_hash", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="shared_result_owner_or_guest_session",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("access", "public"),
                            ("owner__isnull", False),
                            _connector="OR",
                        ),
                        name="owner_only_share_requires_owner",
                    ),
                ],
            },
        ),
    ]
